# Generated by Django 5.1.6 on 2025-02-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avtosalonapp', '0002_carmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
