# Generated by Django 5.1.6 on 2025-02-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uchebniycentrapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
